version: '3.9'
#NOTE: LOCAL DEV ENV ONLY!!!

services:
  # Redis 
  redis:
    image: redis:alpine
    container_name: redis
  # Database
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environmenmt:
      - POSTGRES_DB=postgres # CHANGE NAME IN SOURCE NEWS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    container_name: postgres_db   

  # Django Application
  app:
    build: ./django
    volumes:
      - ./django/:/usr/src/app/
    ports:
      - 8000:8000
    environment: 
      - DEBUG=1
      - SECRET_KEY=django-insecure-o9&qvi9-!#bd1l!pckz&f!yd1#za5fc3=u)2rqerzf6(#)0v49
      - DJANGO_ALLOWED_HOSTS=localhost 0.0.0.0 [::1]
    image: app:django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
      
  # Celery
  celery:
    restart: always
    build: ./django
    command: celery -A backend worker -l DEBUG
    volumes:
      - ./django/:/usr/src/app/
    container_name: celery_worker
    depends_on:
      - db
      - redis
      - app
  celery-beat:
    build: ./django
    command: celery -A backend beat -l INFO
    volumes:
      - ./django/:/usr/src/app/
    container_name: celery_beat
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-o9&qvi9-!#bd1l!pckz&f!yd1#za5fc3=u)2rqerzf6(#)0v49
      - DJANGO_ALLOWED_HOSTS=localhost 0.0.0.0 [::1]
    depends_on:
      - redis

 
 #TODO SEGMENT COMPOSE INTO DIFFERENT DIRS ORGANIZE WITH ENTRY POINTS \
 #cv ''run with --init flag for siganl forwarding 
